import { ArrowLeft, Info, LockKeyhole, MoreVertical, Phone, Search, ShieldCheck } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { ConversationList } from '../components/conversations/ConversationList';
import { MessageBubble } from '../components/messages/MessageContent';
import { WhatsAppStatusBadge } from '../components/whatsapp/WhatsAppStatusBadge';
import { Button } from '../components/ui/button';
import { useConversation, useConversations, useMessages, useWhatsAppAccount } from '../hooks/queries';
import { useAppStore } from '../stores/app-store';

export function ConversationsPage() {
  const { accountId, conversationId } = useParams(); const navigate = useNavigate(); const [search, setSearch] = useState(''); const storeConversation = useAppStore((state) => state.selectConversation); const { data: account } = useWhatsAppAccount(accountId); const { data: conversationItems = [], isLoading: loadingConversations } = useConversations(accountId, search); const activeId = conversationId ?? conversationItems[0]?.id; const { data: conversation } = useConversation(activeId); const { data: messageItems = [], isLoading: loadingMessages } = useMessages(accountId, activeId);
  useEffect(() => { if (activeId) storeConversation(activeId); }, [activeId, storeConversation]);
  const selectedConversation = useMemo(() => conversation ?? conversationItems.find((item) => item.id === activeId), [conversation, conversationItems, activeId]);
  if (!account) return <div className="page-stack"><Link className="back-link" to="/whatsapps"><ArrowLeft size={16} /> Voltar para WhatsApps</Link><div className="empty-state"><Info size={24} /><strong>Número não encontrado</strong><span>Selecione um número corporativo válido.</span></div></div>;
  const selectConversation = (id: string) => navigate(`/whatsapps/${account.id}/conversations/${id}`);
  return <div className="conversation-page"><div className="conversation-top"><Link className="back-link" to="/whatsapps"><ArrowLeft size={16} /> Todos os números</Link><div className="account-context"><div className={`account-avatar avatar-${account.id}`}><span>{account.name.slice(0, 2).toUpperCase()}</span></div><div><h1>{account.name}</h1><span>{account.phoneNumber}</span></div><WhatsAppStatusBadge status={account.status} /></div><div className="context-actions"><Button variant="outline" size="sm" onClick={() => toast.info('Detalhes da conta em modo somente leitura.')}><Info size={15} /> Detalhes</Button><button className="icon-button"><MoreVertical size={18} /></button></div></div><div className="conversation-workspace"><ConversationList conversations={conversationItems} selectedId={activeId} search={search} setSearch={setSearch} onSelect={selectConversation} /><main className="message-panel">{selectedConversation ? <><div className="message-panel-head"><div className="contact-avatar contact-avatar-large">{selectedConversation.contact.name.slice(0, 2).toUpperCase()}<i /></div><div><h2>{selectedConversation.contact.name}</h2><span>{selectedConversation.contact.phone} · {selectedConversation.messageCount} mensagens</span></div><div className="message-panel-actions"><button className="icon-button"><Search size={17} /></button><button className="icon-button"><Phone size={17} /></button></div></div><div className="message-list"><div className="date-divider"><span>Hoje, 12 de agosto</span></div>{loadingMessages ? <div className="message-loading" /> : messageItems.map((message) => <MessageBubble message={message} key={message.id} />)}</div><div className="readonly-banner"><div className="readonly-banner-icon"><LockKeyhole size={16} /></div><div><strong>Modo de conferência · somente leitura</strong><span>Nenhuma mensagem pode ser enviada por esta plataforma.</span></div><ShieldCheck size={16} /></div></> : <div className="message-empty"><div className="message-empty-icon"><Search size={22} /></div><strong>{loadingConversations ? 'Carregando conversas...' : 'Selecione uma conversa'}</strong><span>Escolha uma conversa na lista para consultar o histórico.</span></div>}</main></div></div>;
}
